// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9b2CUArsyVyFLhsw0Kj_gHVksbYvNIwI',
    appId: '1:1080988702876:web:894a4ccd168f7b2a573559',
    messagingSenderId: '1080988702876',
    projectId: 'cardigo-51245',
    authDomain: 'cardigo-51245.firebaseapp.com',
    storageBucket: 'cardigo-51245.firebasestorage.app',
    measurementId: 'G-DLN9MMS5S6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0FMUuWR_T5Ld_5GdVlCOZ_4_0vvqb7-c',
    appId: '1:1080988702876:ios:bdccb9bac339d65d573559',
    messagingSenderId: '1080988702876',
    projectId: 'cardigo-51245',
    storageBucket: 'cardigo-51245.firebasestorage.app',
    iosBundleId: 'com.example.businessCardScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0FMUuWR_T5Ld_5GdVlCOZ_4_0vvqb7-c',
    appId: '1:1080988702876:ios:bdccb9bac339d65d573559',
    messagingSenderId: '1080988702876',
    projectId: 'cardigo-51245',
    storageBucket: 'cardigo-51245.firebasestorage.app',
    iosBundleId: 'com.example.businessCardScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9b2CUArsyVyFLhsw0Kj_gHVksbYvNIwI',
    appId: '1:1080988702876:web:2309b072f72eb1e7573559',
    messagingSenderId: '1080988702876',
    projectId: 'cardigo-51245',
    authDomain: 'cardigo-51245.firebaseapp.com',
    storageBucket: 'cardigo-51245.firebasestorage.app',
    measurementId: 'G-ZCFKN7ZLY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy5J3ENtWemFBjNKt7HtEeJrTnwSVW34M',
    appId: '1:1080988702876:android:024eaddb5049b16c573559',
    messagingSenderId: '1080988702876',
    projectId: 'cardigo-51245',
    storageBucket: 'cardigo-51245.firebasestorage.app',
  );

}